networks:
  backend:

volumes:
  pgdata:
  appdata:
  csvdata:

services:
  db:
    image: postgres:16-alpine
    container_name: iss_db
    environment:
      POSTGRES_DB: monolith
      POSTGRES_USER: monouser
      POSTGRES_PASSWORD: monopass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monouser -d monolith"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - backend
    ports:
      - "5432:5432"

  rust_iss:
    build:
      context: ./services/rust-iss
    container_name: rust_iss
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://monouser:monopass@db:5432/monolith}
      NASA_API_URL: ${NASA_API_URL:-}
      NASA_API_KEY: ${NASA_API_KEY:-}
      FETCH_EVERY_SECONDS: ${FETCH_EVERY_SECONDS:-600}
      WHERE_ISS_URL: ${WHERE_ISS_URL:-https://api.wheretheiss.at/v1/satellites/25544}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8081:3000" 

  php:
    build:
      context: ./services/php-web
    container_name: php_web
    environment:
      JWST_HOST: https://api.jwstapi.com
      JWST_API_KEY: baa96cdf-4a82-45f1-b986-d10a96826442
      JWST_EMAIL: burnfeniks@yandex.ru
      JWST_PROGRAM_ID: "2734"
      ASTRO_APP_ID: "de592f75-b050-4867-b69a-f367e177db87"
      ASTRO_APP_SECRET: "26e38ed7354ebd4ac21d9ca877df2d097f3d318ed0d4aa8598f52b123640da5a761ed0b38d0d2df8fa84fca138f85ba3f7308ecd5da0e939de33d01a12136d166637086b32cdf07cfcb334b4dd6ad2a353c4944d8f082c32e3253f37c1d807374c855b48b3bca7e92f41a5c945e70b5f"
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: monolith
      DB_USERNAME: monouser
      DB_PASSWORD: monopass
    depends_on:
      db:
        condition: service_healthy
      rust_iss:
        condition: service_started
    networks:
      - backend
    volumes:
      - appdata:/var/www/html
      - ./services/php-web/laravel-patches:/opt/laravel-patches:ro

  nginx:
    image: nginx:1.27-alpine
    container_name: web_nginx
    depends_on:
      - php
    volumes:
      - appdata:/var/www/html:ro
      - ./services/php-web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
    ports:
      - "8080:80"

  pascal_legacy:
    build:
      context: ./services/pascal-legacy
    container_name: pascal_legacy
    environment:
      CSV_OUT_DIR: /data/csv
      GEN_PERIOD_SEC: ${PAS_LEGACY_PERIOD:-300}
      PGHOST: db
      PGPORT: 5432
      PGUSER: monouser
      PGPASSWORD: monopass
      PGDATABASE: monolith
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - csvdata:/data/csv
    networks:
      - backend
